# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f55b0d36d0c41ec56f901918f588629c63b226fbde142d91ff6d7cd815162a18dcfb01aa20aa6d6b682a1f8fe606eef9ee0e4e088a54dd7abdbae2a35aaf9f5e

test:
  secret_key_base: 1658aa343ec388f5a9e0bdaaf652be3febf4c20169a973d03fc2627de94dc453e21599378f99fcb48ebc3dd10a399a2debf7405d3c2f177ea3ac5c74e2233970

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
